### ISSUE TITLE
Thermostate configuration

### ISSUE THREAD

**Issue by LucaBors** [peetereczek/HomeAssistantConfig#1]
Hi, first of all thank you for your great work! I've some problem with the thermostate part.
I configure it right with my netatmo thermostate (that's set to 20 degree). When i upload your configuration my thermostate change value to 26 degree. Can you help me to understand what's going on?
 Thank you!

**Comment by peetereczek** [comment]
Hi, this repository is to store and share my personal HA configuration. It's not ment to support any issues arround Home Assistant and related developments. Please reffer directly to HA or used integration component repository.
